name: test

on:
  push: {}
  pull_request: {}

jobs:
  test-bindings:
    name: test-bindings
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        compiler:
          - "g++"
          - "clang++"
        standard:
          - "c++11"
          - "c++20"

    steps:
      - uses: actions/checkout@v3
      - name: build
        env:
          CXX: ${{ matrix.compiler }}
          CXXSTD: ${{ matrix.standard }}
        shell: bash
        working-directory: ${{ github.workspace }}/test
        run: make
